from building import *

cwd = GetCurrentDir()
path = [cwd]

src     = Split("""
board.c
""")

if GetDepend(['BSP_USING_UART']):
    src += ['drv_uart.c']

if GetDepend(['BSP_USING_GPIO']):
    src += ['drv_pin.c']

if GetDepend(['BSP_USING_I2C']):
    src += ['drv_i2c.c']

if GetDepend(['BSP_USING_SPI']):
    src += ['drv_spi.c']

CPPDEFINES = ['CPU_MCIMX6Y2CVM08']

group = DefineGroup('drivers', src, depend = [''], CPPPATH = path, CPPDEFINES=CPPDEFINES)

Return('group')