from building import *

cwd = GetCurrentDir()
src = Split("""
system_MCIMX6Y2.c
""")

if GetDepend(['BSP_USING_GPIO']):
    src += ['drivers/fsl_gpio.c']

path = [cwd,
        cwd + '/drivers']

group = DefineGroup('libraries', src, depend = [''], CPPPATH = path)

Return('group')
