from building import *

cwd = GetCurrentDir()
src = Split("""
system_MCIMX6Y2.c
""")

path = [cwd,
        cwd + '/drivers']

group = DefineGroup('libraries', src, depend = [''], CPPPATH = path)

Return('group')
